### ISSUE TITLE
Waveshare Pico-Lora-sx1262-868m compatibility

### ISSUE THREAD

**Issue by byronczimmer** [ehong-tl/micropySX126X#10]
I've picked up a few of these items:
https://www.waveshare.com/pico-lora-sx1262-868m.htm
And wonder if it would be compatible with this library, since I'd prefer to program them in micropython.

And if so -- what the  sx1262 constructor would be.
I *believe* based on the example in Ping Pong...
sx = SX1262(spi_bus=1, clk=10, mosi=11, miso=12, cs=3, irq=20, rst=15, gpio=2)
that the pinout would be as follows, but I'm unsure of the ?? items.

spi_bus : SPI bus ID               ??
clk : SPI CLK pin                     gp10 ( clock )
mosi : SPI MOSI pin               gp11
miso : SPI MISO pin               gp12
cs : NSS pin                          ( gp3 - chip select? )
irq : DIO1 pin                          gp20 - DIO1
rst : RESET pin                         gp15 - RESET
gpio : BUSY pin                       gp2 -BUSY

Is the SPI BUS the PICO's SPI # for pin 11/12 ( aka 1 ) ?

I look forward to your response.

**Comment by ehong-tl** [comment]
Sorry, I don't have the Waveshare Pico SX1262 and Pico board to try, but based on previous [closed issues](https://github.com/ehong-tl/micropySX126X/issues/7), this library should be compatible with the Waveshare LoRa board. The default constructor in Ping Pong example should be the correct one.

**Comment by byronczimmer** [comment]
Units arrive in the next day or so.
Will let you know.
That other issue definitely helps.  Thank you.

**Comment by Bra1nsen** [comment]
iam currently also working with the waveshare board. i would like to connect it with the the things network.

where does AppEUI and AppKey come into play/configuration?

**Comment by ehong-tl** [comment]
This library does not support LoRaWAN, it only allows you to handle raw LoRa communication.

**Comment by byronczimmer** [comment]
Wanted to share that I got Ping/Pong set up with two of the Waveshare SX1262 Pico Lora Hats on a pair of RPi Picos.
You can add it to your compatibility list. :)
