### ISSUE TITLE
Addition to compatibility list

### ISSUE THREAD

**Issue by Elektroarzt** [ehong-tl/micropySX126X#28]
Hi ... first of all thanks for your excellent work and making it public to the community! Just want to report, that your code also works fine on Heltec WiFi LoRa 32 V3 with SX1262 chip. Only works when using mpy files due to memory issues. Maybe you put it on the compatibility list in your readme.

![image](https://github.com/user-attachments/assets/46c4a03f-29e1-4782-bb59-1f78ca953474)

**Comment by ehong-tl** [comment]
Added to README
